### ISSUE TITLE
EasyTargetDietApi: how to send and receive Intent withou an Activity

### ISSUE THREAD

**Issue by alceurneto** [ARNdroid/EasyTargetDiet#202] opened 2015-04-27 21:58 UTC
Our API need to startActivityForResult to communicate with ETD app.

Without an Activity it seems to be NOT possible. :-(

Some research on StackOverflow about it:
- http://stackoverflow.com/questions/2848775/use-startactivityforresult-from-non-activity
- http://stackoverflow.com/questions/16185694/cant-start-intent-startactivityforresult-from-class?rq=1
- http://stackoverflow.com/questions/3248132/analog-of-startactivityforresult-for-service?lq=1
- http://stackoverflow.com/questions/5218544/android-startactivityforresult-outside-an-activity?lq=1
- http://stackoverflow.com/questions/3448485/startactivityforresult-from-a-service?lq=1
- http://stackoverflow.com/questions/25557087/how-to-get-the-result-from-onactivityresult-inside-another-classoutside-of-the/25557182?noredirect=1#comment39915501_25557182

To some tests being an Activity a delegate of our class API.

If it not works, we need to rethink the interaction third part developer X ETD API.

**Comment by ARNdroid** [comment] 2015-04-28 12:32
A snippet from our test:

``` java
package br.com.arndroid.startactivitytest.api;

import android.app.Activity;
import android.content.Intent;

import br.com.arndroid.startactivitytest.TargetActivity;

public class ApiClass {
    public static final int REQUEST_CODE = 1;

    private static final DelegateActivity sDelegate = new DelegateActivity();

    public static void sendIntent(Activity sender) {
        if (sender == null) {
            sender = sDelegate;
        }
        final Intent intent = new Intent(sender, TargetActivity.class);
        sender.startActivityForResult(intent, REQUEST_CODE);
    }
}
```

The line with `Intent` creation throws this exception:
`
04-28 12:20:10.668    1578-1578/br.com.arndroid.startactivitytest E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalStateException: Could not execute method of the activity
            at android.view.View$1.onClick(View.java:3044)
            at android.view.View.performClick(View.java:3511)
            at android.view.View$PerformClick.run(View.java:14105)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4424)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at android.view.View$1.onClick(View.java:3039)
            at android.view.View.performClick(View.java:3511)
            at android.view.View$PerformClick.run(View.java:14105)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4424)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at android.content.ContextWrapper.getPackageName(ContextWrapper.java:127)
            at android.content.ComponentName.<init>(ComponentName.java:75)
            at android.content.Intent.<init>(Intent.java:3122)
            at br.com.arndroid.startactivitytest.api.ApiClass.sendIntent(ApiClass.java:17)
            at br.com.arndroid.startactivitytest.MainActivity.onTest(MainActivity.java:46)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at android.view.View$1.onClick(View.java:3039)
            at android.view.View.performClick(View.java:3511)
            at android.view.View$PerformClick.run(View.java:14105)
            at android.os.Handler.handleCallback(Handler.java:605)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4424)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)
`

Instead of using the delegate, with a regular Activity (with UI and referenced in `AndroidManifest.xml`) the app behavior is normal.

It's time to rethink the third part developer sequence diagram... sorry.

**Comment by ARNdroid** [comment] 2015-04-28 12:34
We'll close this issue by a push with the work done so far.

**Comment by ARNdroid** [comment] 2015-04-28 12:41
I think we have a last resort: `IPC` before changing third part developers interaction.

**Comment by alceurneto** [comment] 2015-04-28 17:19
To use IPC you need to bind a service. To bind a service, you need be an Activity, a Service or a ContentProvider. We are again with the same problem: we need classes that are created only by the Android System (our API could NOT create this classes in an effective way).

**Closed as completed** 2015-04-29 01:19 UTC
Labels: question
